FROM arm64v8/alpine
RUN apk --no-cache add build-base nodejs npm alpine-sdk  && \
apk del alpine-sdk build-base krb5-dev

ADD package.json package.json
RUN npm install

ADD . .

COPY config-template.json config.json

LABEL databox.type="databox-app-server"

EXPOSE 8080 8181

CMD ["npm","start"]